# -*- coding: utf-8 -*-
"""Math_Master.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nzLP4w2DM9UdjokedH3SHFQ5yD8LUA6O

### **MathMaster : A Python-Based Mathematical Utility System**
"""

import sympy as sp
import math

# ---------------- FUNCTIONS ----------------

# 1. Simple Calculator
def simple_calculator():
    print("\n--- SIMPLE CALCULATOR ---")
    print("1. Addition\n2. Subtraction\n3. Multiplication\n4. Division")
    choice = int(input("Enter operation (1-4): "))
    a = float(input("Enter first number: "))
    b = float(input("Enter second number: "))
    if choice == 1:
        print("Result:", a + b)
    elif choice == 2:
        print("Result:", a - b)
    elif choice == 3:
        print("Result:", a * b)
    elif choice == 4:
        if b != 0:
            print("Result:", a / b)
        else:
            print("Division by zero not allowed")
    else:
        print("Invalid operation")
        input("\nPress Enter to return to Main Menu...")


# 2. Combinatorics
def combinatorics():
    print("\n--- COMBINATORICS ---")
    print("1. Permutation (nPr)\n2. Combination (nCr)")
    choice = int(input("Enter your choice (1-2): "))
    n = int(input("Enter n: "))
    r = int(input("Enter r: "))
    if r > n:
        print("Invalid input: r cannot be greater than n")
    elif choice == 1:
        print("Permutation:", math.perm(n, r))
    elif choice == 2:
        print("Combination:", math.comb(n, r))
    else:
        print("Invalid choice")
        input("\nPress Enter to return to Main Menu...")


# 3. Set Relations
def set_relations():
    print("\n--- SET RELATIONS ---")
    print("1. Union\n2. Intersection\n3. Difference")
    choice = int(input("Enter your choice (1-3): "))
    set1 = set(map(int, input("Enter elements of Set 1 separated by space: ").split()))
    set2 = set(map(int, input("Enter elements of Set 2 separated by space: ").split()))
    if choice == 1:
        print("Union:", set1.union(set2))
    elif choice == 2:
        print("Intersection:", set1.intersection(set2))
    elif choice == 3:
        print("Difference (Set1 - Set2):", set1.difference(set2))
    else:
        print("Invalid choice")
        input("\nPress Enter to return to Main Menu...")


# 4. Matrix Operations
def matrix_operations():
    print("\n--- MATRIX OPERATIONS ---")
    print("1. Determinant\n2. Inverse\n3. Transpose\n4. Solve Linear Equations")
    choice = int(input("Enter your choice (1-4): "))
    n = int(input("Enter size of square matrix (n x n): "))
    matrix = []
    for i in range(n):
        row = []
        for j in range(n):
            element = float(input(f"Enter element [{i+1}][{j+1}]: "))
            row.append(element)
        matrix.append(row)
    M = sp.Matrix(matrix)

    if choice == 1:
        print("Determinant:", M.det())
    elif choice == 2:
        if M.det() != 0:
            print("Inverse:\n", M.inv())
        else:
            print("Inverse does not exist (determinant=0)")
    elif choice == 3:
        print("Transpose:\n", M.T)
    elif choice == 4:
        print("Enter constants for equations (b vector):")
        b = []
        for i in range(n):
            val = float(input(f"b[{i+1}]: "))
            b.append(val)
        try:
            solution = M.LUsolve(sp.Matrix(b))
            print("Solution:\n", solution)
        except:
            print("No unique solution exists")
    else:
        print("Invalid choice")
        input("\nPress Enter to return to Main Menu...")


# 5. Calculus
def calculus():
    print("\n--- CALCULUS ---")
    print("1. Differentiation\n2. Integration")
    choice = int(input("Enter your choice (1-2): "))
    x = sp.symbols('x')
    expr_input = input("Enter expression in terms of x (e.g., x**2 + 3*x + 2): ")
    expr = sp.sympify(expr_input)
    if choice == 1:
        print("Derivative:", sp.diff(expr, x))
    elif choice == 2:
        print("Indefinite Integral:", sp.integrate(expr, x))
    else:
        print("Invalid choice")
        input("\nPress Enter to return to Main Menu...")


# ---------------- MAIN LOOP ----------------
print("===============================================")
print("              MathMaster")
print("A Python-Based Mathematical Utility System")
print("      Developed by Tannistha Banerjee")
print("===============================================")

while True:
    print("\n====== MATHEMATICAL TOOLKIT ======")
    print("1. Simple Calculator")
    print("2. Combinatorics")
    print("3. Set Relations")
    print("4. Matrix Operations")
    print("5. Calculus")
    print("6. Exit")

    try:
        choice = int(input("Enter your choice (1-6): "))
    except:
        print("Invalid input! Enter number 1-6.")
        continue

    if choice == 1:
        simple_calculator()
    elif choice == 2:
        combinatorics()
    elif choice == 3:
        set_relations()
    elif choice == 4:
        matrix_operations()
    elif choice == 5:
        calculus()
    elif choice == 6:
        print("Exiting program...")
        break
    else:
        print("Invalid choice! Please select 1-6.")

